name: publish
on: [push]
jobs:
  publish-simple-app-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build simple-app docker image
        run: |
              docker build . --tag ghcr.io/tom-tan-gtech/simple-app:latest
              docker run ghcr.io/tom-tan-gtech/simple-app:latest
              docker push ghcr.io/tom-tan-gtech/simple-app:latest